<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="35" started-at="2017-04-26T23:43:47Z" finished-at="2017-04-26T23:43:47Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="35" started-at="2017-04-26T23:43:47Z" finished-at="2017-04-26T23:43:47Z">
      <class name="JTest.NewTest">
        <test-method status="PASS" signature="f()[pri:0, instance:JTest.NewTest@a518fc]" name="f" duration-ms="1" started-at="2017-04-26T16:43:47Z" finished-at="2017-04-26T16:43:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="f2()[pri:0, instance:JTest.NewTest@a518fc]" name="f2" duration-ms="0" started-at="2017-04-26T16:43:47Z" finished-at="2017-04-26T16:43:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f2 -->
        <test-method status="PASS" signature="f3()[pri:0, instance:JTest.NewTest@a518fc]" name="f3" duration-ms="0" started-at="2017-04-26T16:43:47Z" finished-at="2017-04-26T16:43:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f3 -->
      </class> <!-- JTest.NewTest -->
      <class name="JTest.nextTest">
        <test-method status="PASS" signature="f()[pri:0, instance:JTest.nextTest@75ace1]" name="f" duration-ms="8" started-at="2017-04-26T16:43:47Z" finished-at="2017-04-26T16:43:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="f2()[pri:0, instance:JTest.nextTest@75ace1]" name="f2" duration-ms="1" started-at="2017-04-26T16:43:47Z" finished-at="2017-04-26T16:43:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f2 -->
        <test-method status="FAIL" signature="f3()[pri:0, instance:JTest.nextTest@75ace1]" name="f3" duration-ms="0" started-at="2017-04-26T16:43:47Z" finished-at="2017-04-26T16:43:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This should return 1 expected:<3> but was:<4>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This should return 1 expected:<3> but was:<4>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at JTest.nextTest.f3(nextTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at JTest.RunTestNG.main(RunTestNG.java:24)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f3 -->
      </class> <!-- JTest.nextTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
